version: '3.8'

volumes:
  puma-sock:
  postgres_volume:

services:

  db:
    image: postgres
    # dbのユーザー名とパスワードでこれが無いとdbが起動できなかった
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # 無くても動くけど指定しておくとdocker-composeを停止してもdbの内容が永続化されるため、指定することが多いと思われる
    # https://matsuand.github.io/docs.docker.jp.onthefly/storage/volumes/
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    # 無くても動くが指定しておくとコンテナ停止時にサービスが再起動してくれる
    # https://docs.docker.jp/v19.03/config/container/start-containers-automatically.html
    restart: always

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ${APP_CODE_PATH_HOST}/public
        target: /var/www/public
        consistency: cached
      - type: volume
        source: puma-sock
        target: /var/www/tmp/sockets
        volume:
          nocopy: true

  app:
    build:
      context: .
      dockerfile: ruby/Dockerfile
    command: bundle exec rails s -b '0.0.0.0'
    # command: bundle exec puma -e development
    ports:
      - ${APP_PORT}:3000
    tty: true
    volumes:
      - type: bind
        source: $APP_CODE_PATH_HOST
        target: /var/www
        consistency: cached
      - type: volume
        source: puma-sock
        target: /var/www/tmp/sockets
        volume:
          nocopy: true
    depends_on:
      - db
